{% set version = "0.9.100.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-taxize
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/taxize_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/taxize/taxize_{{ version }}.tar.gz
  sha256: fae08587d578c35507ffb3521bf33b6272918a78a63baf2870d6529209883a9c

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ape
    - r-cli
    - r-conditionz
    - r-crayon
    - r-crul >=0.7.0
    - r-data.table
    - r-foreach
    - r-jsonlite
    - r-natserv >=1.0.0
    - r-phangorn
    - r-r6
    - r-ritis >=0.7.6
    - r-rotl >=3.0.0
    - r-rredlist
    - r-tibble >=1.2
    - r-wikitaxa >=0.3.0
    - r-worrms >=0.4.0
    - r-xml2 >=1.2.0
    - r-zoo
  run:
    - r-base
    - r-ape
    - r-cli
    - r-conditionz
    - r-crayon
    - r-crul >=0.7.0
    - r-data.table
    - r-foreach
    - r-jsonlite
    - r-natserv >=1.0.0
    - r-phangorn
    - r-r6
    - r-ritis >=0.7.6
    - r-rotl >=3.0.0
    - r-rredlist
    - r-tibble >=1.2
    - r-wikitaxa >=0.3.0
    - r-worrms >=0.4.0
    - r-xml2 >=1.2.0
    - r-zoo

test:
  commands:
    - $R -e "library('taxize')"           # [not win]
    - "\"%R%\" -e \"library('taxize')\""  # [win]

about:
  home: https://docs.ropensci.org/taxize/
  dev_url: https://github.com/ropensci/taxize
  doc_url: https://taxize.dev
  license: MIT
  summary: Interacts with a suite of web 'APIs' for taxonomic tasks, such as getting database specific taxonomic identifiers, verifying species names, getting taxonomic hierarchies, fetching downstream and upstream taxonomic names, getting taxonomic synonyms, converting scientific to common names and vice versa, and more.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
